pipeline {
    agent any
environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-cred') // Docker Hub credentials ID
        IMAGE_NAME = 'sayedkhaledelhawary/nodejs-vo' // Docker Hub username/repo
        IMAGE_TAG = "${env.BUILD_NUMBER}" // Use Jenkins build number as tag
    }
stages {
        stage('Checkout') {
            steps {
                git url: 'https://github.com/mahmoud254/jenkins_nodejs_example.git', branch: 'master'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh '''
                cd /var/jenkins_home/workspace/a/nodeapp
                npm install
                   '''
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
            }
        }
        stage('Push to Docker Hub') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
                sh "docker push ${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
        stage('Deploy') {
            steps {
                sh "docker run -d -p 3000:3000 ${IMAGE_NAME}:${IMAGE_TAG}"
            }
        }
    }
    post {
        always {
            sh 'docker logout'
        }
    }
}

